// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5oXEVbt6H_aw9FBCt04ax3R_2MCes1q4',
    appId: '1:738712257452:web:07c444e1938f2ec7407009',
    messagingSenderId: '738712257452',
    projectId: 'qrattendanceapp-e12e8',
    authDomain: 'qrattendanceapp-e12e8.firebaseapp.com',
    storageBucket: 'qrattendanceapp-e12e8.appspot.com',
    measurementId: 'G-78F72044VZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBF22uZOhwKr4ojQkeBjeCHU8T0-SEN7xM',
    appId: '1:738712257452:android:2b61ee0ea1b50deb407009',
    messagingSenderId: '738712257452',
    projectId: 'qrattendanceapp-e12e8',
    storageBucket: 'qrattendanceapp-e12e8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDfQo91jcgUcVC721m1gMhtrzgrSkO6zvM',
    appId: '1:738712257452:ios:2193d2874939f3e0407009',
    messagingSenderId: '738712257452',
    projectId: 'qrattendanceapp-e12e8',
    storageBucket: 'qrattendanceapp-e12e8.appspot.com',
    iosBundleId: 'com.example.qrattendanceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDfQo91jcgUcVC721m1gMhtrzgrSkO6zvM',
    appId: '1:738712257452:ios:74d2bc97f9146129407009',
    messagingSenderId: '738712257452',
    projectId: 'qrattendanceapp-e12e8',
    storageBucket: 'qrattendanceapp-e12e8.appspot.com',
    iosBundleId: 'com.example.qrattendanceapp.RunnerTests',
  );
}
